[package]
name = "iced-http-lens"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { git = "https://github.com/iced-rs/iced.git", version = "0.13.0-dev", features = [
    "tokio",
] }
reqwest = "0.12.7"
strum = "0.26.3"
strum_macros = "0.26.4"
